In [3]:
import sklearn
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv')
df.columns=list('ABCDEFGHI')
df

A    B   C   D    E     F      G   H  I
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [40]:
from sklearn.model_selection import train_test_split
x,x1,y,y1=train_test_split(df.drop('I',axis=1),df["I"],test_size=0.2)
x=x.values
x1=x1.values
y=y.values
y1=y1.values

In [41]:
from sklearn.ensemble import AdaBoostClassifier
a=AdaBoostClassifier()
a.fit(x,y)

AdaBoostClassifier()

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y1,a.predict(x1))

0.7337662337662337

In [43]:
from sklearn.tree import DecisionTreeClassifier
from math import log
class AdaBoost:
    def __init__(self,n_estimators=20):
        self.n_estimators=n_estimators
    
    def fit(self,x,y):
        self.models=[]
        self.model_weights=[]
        d=np.ones(x.shape[0])/x.shape[0]
        for i in range(self.n_estimators):
            m=DecisionTreeClassifier(max_depth=1)
            m.fit(x,y,sample_weight=d)
            res=m.predict(x)
            k=(res!=y)
            s=k.sum()/len(y)
            a=0.5*(log((1-s)/s))
            for j in range(len(d)):
                if(res[j]==y[j]):
                    d[j]*=np.exp(-a)
                else:
                    d[j]*=np.exp(a)
            d=d/d.sum()
            self.models.append(m)
            self.model_weights.append(a)
    
    def predict(self,x):
        l=[]
        for i in x:
            d={}
            for j in range(self.n_estimators):
                res=self.models[j].predict([i])
                if(res[0] in d):
                    d[res[0]]+=self.model_weights[j]
                else:
                    d[res[0]]=self.model_weights[j]
            l1=list(d.items())
            l1.sort(key=lambda x:x[1],reverse=True)
            l.append(l1[0][0])
        return np.array(l)

In [50]:
m=AdaBoost(n_estimators=10)
m.fit(x,y)

In [51]:
accuracy_score(m.predict(x1),y1)

0.7142857142857143

In [52]:
m.predict(x1)

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
      dtype=int64)

In [53]:
y1

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
      dtype=int64)

In [54]:
a.predict(x1)

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1],
      dtype=int64)

In [55]:
m.model_weights

[0.5161389074238841,
 0.30790698857838744,
 0.13291423558258003,
 0.33317449370261054,
 0.24110754486236247,
 0.22046974815091205,
 0.311492700934006,
 0.13623632689412604,
 -0.25846027451674347,
 -0.25846027451674347]